version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      CORS_ORIGIN: http://localhost:5173
    networks:
      - sykell-network

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      VITE_BASE_API_URL: http://localhost:8080
      VITE_BASE_API_TOKEN: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh5dW53b29fY2hvIn0.nz6YQhWHm-qlrSPdk6f30Ho5-3Si4qaiBiw1YvCYCBc"
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - sykell-network

networks:
  sykell-network:
    driver: bridge
